### ISSUE TITLE
抖音返回的json格式有点问题

### ISSUE THREAD

**Issue by zhuxiaole** [Borber/seam#119]
`{"default_resolution":"HD1","extra":{"anchor_interact_profile":0,"audience_interact_profile":0,"bframe_enable":false,"bitrate_adapt_strategy":0,"bytevc1_enable":false,"default_bitrate":0,"fps":0,"gop_sec":0,"h265_enable":false,"hardware_encode":false,"height":1080,"max_bitrate":0,"min_bitrate":0,"roi":false,"sw_roi":false,"video_profile":0,"width":1920},"flv_pull_url":{"FULL_HD1":"http://pull-l3.douyincdn.com/third/stream-112894897391927775_uhd.flv?auth_key=1682881138-0-0-45f43cf02cf7d21f731d6651ba777a7e","HD1":"http://pull-l3.douyincdn.com/third/stream-112894897391927775_hd.flv?auth_key=1682881138-0-0-e66c5df85749620fbaf3ba7aceb9055a","SD1":"http://pull-l3.douyincdn.com/third/stream-112894897391927775_ld.flv?auth_key=1682881138-0-0-3da644010272ffe02c7cf79d572a1bdc","SD2":"http://pull-l3.douyincdn.com/third/stream-112894897391927775_sd.flv?auth_key=1682881138-0-0-5e2e22e8dd75c160979481fd40163d07"},"hls_pull_url":"http://pull-l3.douyincdn.com/third/stream-112894897391927775_hd.m3u8?auth_key=1682881138-0-0-57e26e847fe730bf18066b37a8d7e58b","hls_pull_url_map":{"FULL_HD1":"http://pull-l3.douyincdn.com/third/stream-112894897391927775_uhd.m3u8?auth_key=1682881138-0-0-aa10816dd85a5803c5809ce769c5ca57","HD1":"http://pull-l3.douyincdn.com/third/stream-112894897391927775_hd.m3u8?auth_key=1682881138-0-0-57e26e847fe730bf18066b37a8d7e58b","SD1":"http://pull-l3.douyincdn.com/third/stream-112894897391927775_ld.m3u8?auth_key=1682881138-0-0-8005e4937111ef97df7bd0e2db4df8f1","SD2":"http://pull-l3.douyincdn.com/third/stream-112894897391927775_sd.m3u8?auth_key=1682881138-0-0-d18b29cd25dce106ae63275051725592"},"live_core_sdk_data":{"pull_data":{"options":{"default_quality":{"additional_content":"","disable":0,"fps":0,"level":3,"name":"超清","resolution":"1280x720","sdk_key":"hd","v_bit_rate":0,"v_codec":"264"},"qualities":[{"additional_content":"","disable":0,"fps":25,"level":1,"name":"标清","resolution":"960x540","sdk_key":"ld","v_bit_rate":1000000,"v_codec":"264"},{"additional_content":"","disable":0,"fps":30,"level":2,"name":"高清","resolution":"1280x720","sdk_key":"sd","v_bit_rate":2000000,"v_codec":"264"},{"additional_content":"","disable":0,"fps":30,"level":3,"name":"超清","resolution":"1280x720","sdk_key":"hd","v_bit_rate":4000000,"v_codec":"264"},{"additional_content":"","disable":0,"fps":45,"level":4,"name":"蓝光","resolution":"1920x1080","sdk_key":"uhd","v_bit_rate":6417000,"v_codec":"264"},{"additional_content":"","disable":0,"fps":0,"level":5,"name":"原画","resolution":"1920x1080","sdk_key":"origin","v_bit_rate":6417000,"v_codec":"264"}]},"stream_data":"{\"common\":{\"session_id\":\"037-202304240328588C62055B3546270B088B\",\"rule_ids\":\"{\\\"ab_version_trace\\\":null,\\\"sched\\\":\\\"{\\\\\\\"result\\\\\\\":{\\\\\\\"hit\\\\\\\":\\\\\\\"default\\\\\\\",\\\\\\\"cdn\\\\\\\":541}}\\\"}\",\"app_id\":\"100102\"},\"data\":{\"uhd\":{\"main\":{\"flv\":\"http://pull-l3.douyincdn.com/third/stream-112894897391927775_uhd.flv?auth_key=1682881138-0-0-45f43cf02cf7d21f731d6651ba777a7e\",\"hls\":\"http://pull-l3.douyincdn.com/third/stream-112894897391927775_uhd.m3u8?auth_key=1682881138-0-0-aa10816dd85a5803c5809ce769c5ca57\",\"cmaf\":\"\",\"dash\":\"\",\"lls\":\"http://pull-lls-l3.douyincdn.com/third/stream-112894897391927775_uhd.sdp?auth_key=1682881138-0-0-e46c60b1b637060e73322453f8c0738a\",\"tsl\":\"\",\"tile\":\"\",\"sdk_params\":\"{\\\"VCodec\\\":\\\"h264\\\",\\\"vbitrate\\\":6000000,\\\"resolution\\\":\\\"1920x1080\\\",\\\"gop\\\":4,\\\"drType\\\":\\\"sdr\\\"}\"}},\"hd\":{\"main\":{\"flv\":\"http://pull-l3.douyincdn.com/third/stream-112894897391927775_hd.flv?auth_key=1682881138-0-0-e66c5df85749620fbaf3ba7aceb9055a\",\"hls\":\"http://pull-l3.douyincdn.com/third/stream-112894897391927775_hd.m3u8?auth_key=1682881138-0-0-57e26e847fe730bf18066b37a8d7e58b\",\"cmaf\":\"\",\"dash\":\"\",\"lls\":\"http://pull-lls-l3.douyincdn.com/third/stream-112894897391927775_hd.sdp?auth_key=1682881138-0-0-6e0a802e9e9a5e502bc124087cb7cd3d\",\"tsl\":\"\",\"tile\":\"\",\"sdk_params\":\"{\\\"VCodec\\\":\\\"h264\\\",\\\"vbitrate\\\":4000000,\\\"resolution\\\":\\\"1280x720\\\",\\\"gop\\\":4,\\\"drType\\\":\\\"sdr\\\"}\"}},\"sd\":{\"main\":{\"flv\":\"http://pull-l3.douyincdn.com/third/stream-112894897391927775_sd.flv?auth_key=1682881138-0-0-5e2e22e8dd75c160979481fd40163d07\",\"hls\":\"http://pull-l3.douyincdn.com/third/stream-112894897391927775_sd.m3u8?auth_key=1682881138-0-0-d18b29cd25dce106ae63275051725592\",\"cmaf\":\"\",\"dash\":\"\",\"lls\":\"http://pull-lls-l3.douyincdn.com/third/stream-112894897391927775_sd.sdp?auth_key=1682881138-0-0-57f50d0387ed6d406fbaa08638825208\",\"tsl\":\"\",\"tile\":\"\",\"sdk_params\":\"{\\\"VCodec\\\":\\\"h264\\\",\\\"vbitrate\\\":2000000,\\\"resolution\\\":\\\"1280x720\\\",\\\"gop\\\":4,\\\"drType\\\":\\\"sdr\\\"}\"}},\"ao\":{\"main\":{\"flv\":\"http://pull-l3.douyincdn.com/third/stream-112894897391927775.flv?auth_key=1682881138-0-0-e68eaa6da362b7010b9bb510f434bd39\\u0026only_audio=1\",\"hls\":\"\",\"cmaf\":\"\",\"dash\":\"\",\"lls\":\"\",\"tsl\":\"\",\"tile\":\"\",\"sdk_params\":\"{\\\"VCodec\\\":\\\"h264\\\",\\\"vbitrate\\\":0,\\\"resolution\\\":\\\"\\\",\\\"gop\\\":4,\\\"drType\\\":\\\"sdr\\\"}\"}},\"ld\":{\"main\":{\"flv\":\"http://pull-l3.douyincdn.com/third/stream-112894897391927775_ld.flv?auth_key=1682881138-0-0-3da644010272ffe02c7cf79d572a1bdc\",\"hls\":\"http://pull-l3.douyincdn.com/third/stream-112894897391927775_ld.m3u8?auth_key=1682881138-0-0-8005e4937111ef97df7bd0e2db4df8f1\",\"cmaf\":\"\",\"dash\":\"\",\"lls\":\"http://pull-lls-l3.douyincdn.com/third/stream-112894897391927775_ld.sdp?auth_key=1682881138-0-0-33f529aafa060bda9f9810e095ea20cc\",\"tsl\":\"\",\"tile\":\"\",\"sdk_params\":\"{\\\"VCodec\\\":\\\"h264\\\",\\\"vbitrate\\\":1000000,\\\"resolution\\\":\\\"960x540\\\",\\\"gop\\\":4,\\\"drType\\\":\\\"sdr\\\"}\"}},\"md\":{\"main\":{\"flv\":\"https://pull-l3-admin.douyincdn.com/third/stream-112894897391927775_md.flv?auth_key=1682881138-0-0-b362f5380fc7567e1c1846c7a9dfda8f\",\"hls\":\"http://pull-l3.douyincdn.com/third/stream-112894897391927775_md.m3u8?auth_key=1682881138-0-0-cd40b38123c664d8b011065c3a9b17e2\",\"cmaf\":\"\",\"dash\":\"\",\"lls\":\"http://pull-lls-l3.douyincdn.com/third/stream-112894897391927775_md.sdp?auth_key=1682881138-0-0-8791998d111137e959a66dee6e9d7cef\",\"tsl\":\"\",\"tile\":\"\",\"sdk_params\":\"{\\\"VCodec\\\":\\\"h264\\\",\\\"vbitrate\\\":800000,\\\"resolution\\\":\\\"640x360\\\",\\\"gop\\\":4,\\\"drType\\\":\\\"sdr\\\"}\"}},\"origin\":{\"main\":{\"flv\":\"http://pull-l3.douyincdn.com/third/stream-112894897391927775_or4.flv?auth_key=1682881138-0-0-dec203cf131be27638f3baecd1ad45a2\",\"hls\":\"http://pull-l3.douyincdn.com/third/stream-112894897391927775_or4.m3u8?auth_key=1682881138-0-0-9d8100a5c53dddceaeb20556fa5edad5\",\"cmaf\":\"\",\"dash\":\"\",\"lls\":\"http://pull-lls-l3.douyincdn.com/third/stream-112894897391927775_or4.sdp?auth_key=1682881138-0-0-1bce251e01e3507a257480694eb99e55\",\"tsl\":\"\",\"tile\":\"\",\"sdk_params\":\"{\\\"VCodec\\\":\\\"h264\\\",\\\"vbitrate\\\":6417000,\\\"resolution\\\":\\\"1920x1080\\\",\\\"gop\\\":4,\\\"drType\\\":\\\"sdr\\\"}\"}}}}"}},"pull_datas":{},"stream_orientation":2}
{
  "title": "今天是爱谁谁猫",
  "nodes": [
    {
      "format": "flv",
      "url": "http://pull-l3.douyincdn.com/third/stream-112894897391927775_uhd.flv?auth_key=1682881138-0-0-45f43cf02cf7d21f731d6651ba777a7e"
    },
    {
      "format": "m3u",
      "url": "http://pull-l3.douyincdn.com/third/stream-112894897391927775_uhd.m3u8?auth_key=1682881138-0-0-aa10816dd85a5803c5809ce769c5ca57"
    }
  ]
}`

看起来是两个json拼接到一起了，用程序去解析会出错。

**Comment by Borber** [comment]
已经修复了  https://github.com/Borber/seam/releases/tag/v0.1.24

**Comment by zhuxiaole** [comment]
感谢！
