### ISSUE TITLE
linux下需要把msvcrt模块替换为getch模块

### ISSUE THREAD

**Issue by Duter2016** [Borber/seam#12]
msvcrt模块只能在win下运行，在linux下没有这个模块，我替换为getch模块后，可以运行！

即把
`import msvcrt` 

改为
`import getch`

**Comment by shyboy** [comment]
Mac里面这两个都没有用。。。。

**Comment by Borber** [comment]
目前使用rust进行重构了 后续所有平台均会提供直接可执行文件， 将不再存在这个问题
