### ISSUE TITLE
分享一个万能直播格式;顺便请教一下这个是什么直播格式

### ISSUE THREAD

**Issue by suger520HT** [Borber/seam#132]
http://live.aptvapp.com/live/douyu/252140
http://live.aptvapp.com/live/huya/660000
http://live.aptvapp.com/live/直播平台/房间号
依次类推我亲测有效

**Comment by Borber** [comment]
额, 没太听懂, 这是别人写好的服务好像

**Comment by suger520HT** [comment]
我就是不清楚才问的 我也感觉像是别人搭建的服务器来解析直播源的

**Comment by Borber** [comment]
> 我就是不清楚才问的 我也感觉像是别人搭建的服务器来解析直播源的

是的， 接口的样式只是作者这么设定而已

**Comment by suger520HT** [comment]
> > 我就是不清楚才问的 我也感觉像是别人搭建的服务器来解析直播源的
> 
> 是的， 接口的样式只是作者这么设定而已

感觉效果一般 斗鱼的有些好像用不了

**Comment by Borber** [comment]
> > > 我就是不清楚才问的 我也感觉像是别人搭建的服务器来解析直播源的
> > 
> > 
> > 是的， 接口的样式只是作者这么设定而已
> 
> 感觉效果一般 斗鱼的有些好像用不了

嗯嗯， 本项目后期也会提供在线接口服务的， 或自部署方案

**Comment by suger520HT** [comment]
[M3U8.log](https://github.com/Borber/seam/files/11437427/M3U8.log)
这是 别人给我的你们看一下 我改了扩展名方便上传 你们改m3u就可以但是好像失效了
