### ISSUE TITLE
斗鱼的又又又又失效了

### ISSUE THREAD

**Issue by suger520HT** [Borber/seam#141]
大佬修复下

**Comment by Borber** [comment]
ok 等我下班， 上班摸鱼不敢开直播

**Comment by Borber** [comment]
我这边测试没有什么问题呀， 能具体描述一下问题吗？

**Comment by suger520HT** [comment]
> 我这边测试没有什么问题呀， 能具体描述一下问题吗？

cdn失效了

**Comment by Borber** [comment]
![image](https://github.com/Borber/seam/assets/30563826/400b1144-a7f7-4815-b985-4ac7e658a39a)
我这边测试没有问题 ， 目前有三个链接， 你都试试， 后面发现新的 CDN 会继续添加

**Comment by MungJI** [comment]
斗鱼移动端获取的这个源，能切换清晰度吗？我_4000.m3u8这样发现不行，是方式不对吗

**Comment by Borber** [comment]
> 斗鱼移动端获取的这个源，能切换清晰度吗？我_4000.m3u8这样发现不行，是方式不对吗

现在确实是从移动端的接口获取的, 我记得这个后缀是不影响的, 可能是直播间的源数据没有达到 _4000 的清晰度, 有些网页上的超清高清选项其实本身链接的质量就不是很高

**Comment by Borber** [comment]
斗鱼现在还有问题吗? 我这边好像没有问题, 如果没有的话我就close喽

**Comment by suger520HT** [comment]
> 斗鱼现在还有问题吗? 我这边好像没有问题, 如果没有的话我就close喽

没问题了
