### ISSUE TITLE
douyin未开播直播间获取信息触发报错，程序退出

### ISSUE THREAD

**Issue by JusticeGu** [Borber/seam#142]
douyin未开播直播间获取信息会触发报错位置在douyin 第43行。
 thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/live/douyin.rs:43:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Borber** [comment]
感谢 我去看看

**Comment by Borber** [comment]
已解决
