### ISSUE TITLE
虎牙绝大多数都不好用了

### ISSUE THREAD

**Issue by 1312644** [Borber/seam#159]
哪位好心人能修复下，虎牙三天两头搞事情。
或者有其他在线代理推荐的么，常见的几个或者经常无法访问，或者解析结果不能用。

**Comment by Borber** [comment]
我近期修复一下

**Comment by suger520HT** [comment]
斗鱼好像又变了

**Comment by Borber** [comment]
虎牙 GUI 版本, 已修复, 请使用最新版 GUI 解析

**Comment by suger520HT** [comment]
> 虎牙 GUI 版本, 已修复, 请使用最新版 GUI 解析

下载那个文件  需要什么依赖
