### ISSUE TITLE
b站报错

### ISSUE THREAD

**Issue by unknownUser99999** [Borber/seam#183]
seam bili 13550856
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', seam_core/src/live/bili.rs:37:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Borber** [comment]
收到

**Comment by Borber** [comment]
你看看现在 gui 版本的有问题吗? 我这边解析没有出现这个问题

**Comment by unknownUser99999** [comment]
> 你看看现在 gui 版本的有问题吗? 我这边解析没有出现这个问题

这个是linux版本的问题，不是gui，就是cli。暂时没在用linux，无所谓了
