### ISSUE TITLE
问下linux适合哪个版本的

### ISSUE THREAD

**Issue by unknownUser99999** [Borber/seam#190]
ubuntu提示可知性文件格式错误

**Comment by unknownUser99999** [comment]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', seam_core/src/live/douyu.rs:210:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
已放弃

**Comment by Borber** [comment]
> 我用了一个版本不提示文件格式错误之后 运行douyu的直播间出现了下面的错误
> 
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', seam_core/src/live/douyu.rs:210:38 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 已放弃

放弃啥呀, 咱会帮你解决的嘛

**Comment by Borber** [comment]
v0.1.29  seam-v0.1.29.x86_64-unknown-linux-gnu.tar.xz 测试通过, 我的环境时 github 的 codespace 上的 ubuntu, 不用下载 jin 直接单文件使用即可

![image](https://github.com/Borber/seam/assets/30563826/548b7c98-a7ef-4102-ad16-4296e92838bd)

**Comment by unknownUser99999** [comment]
> v0.1.29 seam-v0.1.29.x86_64-unknown-linux-gnu.tar.xz 测试通过, 我的环境时 github 的 codespace 上的 ubuntu, 不用下载 jin 直接单文件使用即可
> 
> ![image](https://user-images.githubusercontent.com/30563826/257715190-548b7c98-a7ef-4102-ad16-4296e92838bd.png)
我使用了vpn之后他会卡住不动，关了就好了，这很奇怪

**Comment by Borber** [comment]
> > v0.1.29 seam-v0.1.29.x86_64-unknown-linux-gnu.tar.xz 测试通过, 我的环境时 github 的 codespace 上的 ubuntu, 不用下载 jin 直接单文件使用即可
> > ![image](https://user-images.githubusercontent.com/30563826/257715190-548b7c98-a7ef-4102-ad16-4296e92838bd.png)
> > 我使用了vpn之后他会卡住不动，关了就好了，这很奇怪
> > 参数好像变了，-l -i,原来的有啥问题吗

改版了, 之前core的写法不适合 gui 以及用户自己调用lib, 现在改动之后动态派发可以更简单的匹配平台和房间号, 整体编写难度大大降低, 但整体又更加和谐, 可以去除大概几百行代码

**Comment by unknownUser99999** [comment]
> > > v0.1.29 seam-v0.1.29.x86_64-unknown-linux-gnu.tar.xz 测试通过, 我的环境时 github 的 codespace 上的 ubuntu, 不用下载 jin 直接单文件使用即可 
> > > ![图像](https://user-images.githubusercontent.com/30563826/257715190-548b7c98-a7ef-4102-ad16-4296e92838bd.png)
> > > 我使用了vpn之后他会卡住不动，关了就好了，这很奇怪 
> > > 参数好像变了，-l -i,原来的有啥问题吗
> 
> 改版了, 之前core的写法不适合 gui 以及用户自己调用lib, 现在改动之后动态派发可以更简单的匹配平台和房间号, 整体编写难度大大降低, 但整体又更加和谐, 可以去除大概几百行代码

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/core/src/live/douyin.rs:47:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace  
可是还是有这个错误啊，这个rust_backtrace是环境问题吗

**Comment by Borber** [comment]
抖音这个是因为 cookie 模块目前调整  有说明的。

**注意事项: 目前抖音和快手因为 cookie 模块的加入进行了较大修改, 所以目前不支持获取这两个平台的直播源**

**Comment by unknownUser99999** [comment]
> 抖音这个是因为 cookie 模块目前调整 有说明的。
> 
> **注意事项: 目前抖音和快手因为 cookie 模块的加入进行了较大修改, 所以目前不支持获取这两个平台的直播源 **

好吧，我还以为我这边出错了

**Comment by Borber** [comment]
cookie 已经搞定， 我这边先把 issue关了哈
