### ISSUE TITLE
卡巴斯基报毒

### ISSUE THREAD

**Issue by iLGZH-y** [Borber/seam#196]
OS: windows10

![image](https://github.com/Borber/seam/assets/82648854/f1713fe1-b35b-4d5f-9406-53b20fa6156d)
事件: 检测到恶意对象
应用程序: seam
用户: 
用户类型: 活动用户
组件: 系统监控
结果说明: 检测到
类型: 木马
名称: PDM:Trojan.Win32.Generic
威胁级别: 高
对象类型: 进程
对象路径: d:\downloads\idm\programs
对象名称: seam_0.1.4_x64-setup.exe
原因: 数据库
数据库发布日期: 昨天，2023/8/10 12:59:00

![image](https://github.com/Borber/seam/assets/82648854/009a9ed6-7961-4752-8919-4c4f0a20f941)

事件: 检测到恶意对象
用户: 
用户类型: 活动用户
应用程序名称: seam_0.1.4_x64-setup.exe
应用程序路径: D:\Downloads\IDM\Programs
组件: 文件反病毒
结果说明: 检测到
类型: 木马
名称: HEUR:Trojan.Win32.Agent.gen
精确度: 启发式分析
威胁级别: 高
对象类型: 文件
对象名称: #
对象路径: D:\Program Files\seam_gui\uninstall.exe//
MD5: 498D02F42C6773B1146B4B68701B4485
原因: 机器学习
数据库发布日期: 昨天，2023/8/10 12:59:00

**Comment by suger520HT** [comment]
请教一下我没用过这个软件 下载那些东西

**Comment by Borber** [comment]
https://www.microsoft.com/en-us/wdsi/submission/705e7ed1-dfe3-4c51-9b55-c614101d5bc6
