### ISSUE TITLE
关于使用Tauri作为GUI框架的一个提议

### ISSUE THREAD

**Issue by eweca-d** [Borber/seam#20]
我看关于“线路”部分的说明里包含有GUI，然后作者的repos有不少使用TS/JS作为主力语言，再加上本项目对UI性能也不是特别敏感，所以我提议使用Tauri作用GUI的备选项甚至首选项。

同时提议将现有代码封装成为一个库，变成类似：

seam
|-  seam_core（核心代码）
|-  seam_cli（命令行程序）
|-  seam_tauri (GUI程序）
|-  ....

其中seam_core作为核心库供cli和tauri调用。

**Comment by Borber** [comment]
确实是打算使用tauri来开发gui的, 以及分库的操作也有在计划中, 预计在春节左右开始, , 后续也会探索插件化的可能

**Comment by eweca-d** [comment]
非常期待了，GUI的话感觉用起来会很方便，不然在cmd里复制粘贴链接也会成为一个麻烦事。
