### ISSUE TITLE
韩国平台

### ISSUE THREAD

**Issue by garyvalue** [Borber/seam#21]
https://www.pandalive.co.kr/
https://www.popkontv.com/
https://www.winktv.co.kr/
https://www.flextv.co.kr/
https://rosetv.co.kr/
https://mafiatv.co.kr/
http://afreecatv.com/

**Comment by Borber** [comment]
https://rosetv.co.kr/ 全部主播均需要账号， 故而推迟支持

**Comment by Borber** [comment]
感谢大佬提供的账号, 韩国平台将开始陆续转为 private 项目提供 在线端口. 下周内上线试用.
