### ISSUE TITLE
我发现一个问题，即使我从浏览器那抓取的url都不能在potplayer播放

### ISSUE THREAD

**Issue by unknownUser99999** [Borber/seam#211]
感觉很奇怪啊

**Comment by Borber** [comment]
试试 mpv

**Comment by unknownUser99999** [comment]
> 
mpv能访问2次吗

**Comment by unknownUser99999** [comment]
> 1. 试试 mpv
> 
>     2. 有些链接只能访问一次，二次访问就会失效

mpv能访问2次吗

**Comment by unknownUser99999** [comment]
> > 1. 试试 mpv 
> >    
> >    2. 有些链接只能访问一次，二次访问就会失效
> 
> mpv能访问2次吗



> 1. 试试 mpv
> 
>     2. 有些链接只能访问一次，二次访问就会失效

最关键的是我用seam获取的也无法在potplayer中打开，mpv可以正常使用吗

**Comment by unknownUser99999** [comment]
> 

斗鱼的链接在国外看不了

**Comment by unknownUser99999** [comment]
> 1. 试试 mpv
> 
>     2. 有些链接只能访问一次，二次访问就会失效

斗鱼的链接在国外看不了
