### ISSUE TITLE
Windows上GUI无法读取config

### ISSUE THREAD

**Issue by turtlegxb** [Borber/seam#214]
我将seam.exe和config.toml放在一个文件夹，但读取不到，始终显示please set play bin
我查了一下，有可能跟这个有关，不一定好修复
https://github.com/rust-lang/rust/issues/59117
希望能够增加config指定地址的参数，或者在log里增加一些提示

**Comment by Borber** [comment]
> 我将seam.exe和config.toml放在一个文件夹，但读取不到，始终显示please set play bin 我查了一下，有可能跟这个有关，不一定好修复 [rust-lang/rust#59117](https://github.com/rust-lang/rust/issues/59117) 希望能够增加config指定地址的参数，或者在log里增加一些提示

发一下你的配置

**Comment by Borber** [comment]
问题解决了吗?

**Comment by turtlegxb** [comment]
`# 播放器路径或命令
# 请自行安装播放器, 请确认它可以通过命令行+链接打开视频文件
[play]
bin = "D:\\Program Files\\DAUM\\PotPlayer\\PotPlayerMini64.exe" 
# 播放器参数
args = []

# headers 支持所有合法 http 请求头字段
# global 为全局请求头, 会被各平台请求头覆盖
# 请注意 不要覆盖虎牙的 user-agent, 否则会导致获取失败
[headers.global]
# user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.200"
# 各平台
[headers.douyin]
cookie = "xxxx"

[headers.ks]
cookie = "xxxx"


# [rid]: 房间号
# [title]: 标题
# [time]: 时间戳
# [date]: 日期
[file_name]
# 录制文件标题
video = "[rid]-[title]-[date]-[time]"
# danmu文件标题
danmu = "[rid]-[title]-[date]-[time]"
`

**Comment by turtlegxb** [comment]
解决了
