### ISSUE TITLE
抖音已失效

### ISSUE THREAD

**Issue by Lonely233233** [Borber/seam#229]
![image](https://github.com/Borber/seam/assets/106970209/0355ea8f-0c80-4d81-8b0c-0ad36aafedfe)
![image](https://github.com/Borber/seam/assets/106970209/4c2641d5-09ab-4742-add8-960405bc9143)

**Comment by Borber** [comment]
https://github.com/Borber/seam/releases/tag/v_gui.0.1.8 已修复， 请下载最新版软件
