### ISSUE TITLE
抖音获取失效了，网页抓取没有RENDER_DATA这个字段了

### ISSUE THREAD

**Issue by lyleaf-81** [Borber/seam#230]
抖音获取失效了，网页抓取没有
![image](https://github.com/Borber/seam/assets/63569552/b22ac1c1-d7b2-458e-824d-8069b8f1b222)
RENDER_DATA这个字段了

**Comment by Borber** [comment]
https://github.com/Borber/seam/releases/tag/v_gui.0.1.8 已修复， 请下载最新版软件
