### ISSUE TITLE
使用v_cli.0.1.35 解析抖音出错

### ISSUE THREAD

**Issue by xuzhihans** [Borber/seam#232]
使用v_cli.0.1.35 解析抖音出错
出现报错：
[root@douyin]# ./seam -l douyin -i 120927421535
Request error: error decoding response body: EOF while parsing a value at line 1 column 0

偶尔可以解析成功

**Comment by ggrreeeedd** [comment]
抖音快手现在好像必须要cookies了，能不能不要cookies

**Comment by xuzhihans** [comment]
我在配置文件里面写了cookies，是不是我运行了多个seam进程，并且循环执行，导致的？
因为我在另外一台机器上（不同的公网ip）执行seam是没有报错的

**Comment by Borber** [comment]
> 抖音快手现在好像必须要cookies了，能不能不要cookies

因为必须要 cookie 了， 所以不能不要 cookie 🤣

**Comment by Borber** [comment]
> 我在配置文件里面写了cookies，是不是我运行了多个seam进程，并且循环执行，导致的？ 因为我在另外一台机器上（不同的公网ip）执行seam是没有报错的

是不是请求的太频繁导致的？ ip 被封了或者重新获取一下 cookie 试试

**Comment by ggrreeeedd** [comment]
> > 抖音快手现在想要必须要cookies了，能不能不要cookies
> 
> 因为必须要 cookie 了，所以不能不要 cookie 🤣

游客模式最高清晰度是高清

之前还在使用Seamv0.1.28+SeamPotPlayer，可以使用原画质，昨天开始就不能用了

**Comment by xuzhihans** [comment]
> > 我在配置文件里面写了cookies，是不是我运行了多个seam进程，并且循环执行，导致的？ 因为我在另外一台机器上（不同的公网ip）执行seam是没有报错的
> 
> 是不是请求的太频繁导致的？ ip 被封了或者重新获取一下 cookie 试试

应该是ip被封了，我重新连接了网络，重新获取了wan口ip地址，目前看来正常，我降低请求频率观察一下
之前是没有这个问题的，就是从昨天你发布了这个版本开始，就这样了

**Comment by Borber** [comment]
> > > 我在配置文件里面写了cookies，是不是我运行了多个seam进程，并且循环执行，导致的？ 因为我在另外一台机器上（不同的公网ip）执行seam是没有报错的
> > 
> > 
> > 是不是请求的太频繁导致的？ ip 被封了或者重新获取一下 cookie 试试
> 
> 应该是ip被封了，我重新连接了网络，重新获取了wan口ip地址，目前看来正常，我降低请求频率观察一下 之前是没有这个问题的，就是从昨天你发布了这个版本开始，就这样了

因为最近抖音改了代码， 现在有专门的接口了， 可能会检测请求， 之前是直接从网页扒数据就行， 他监控不了

**Comment by Borber** [comment]
> > > 抖音快手现在想要必须要cookies了，能不能不要cookies
> > 
> > 
> > 因为必须要 cookie 了，所以不能不要 cookie 🤣
> 
> 游客模式最高清晰度是高清
> 
> 之前还在使用Seamv0.1.28+SeamPotPlayer，可以使用原画质，昨天开始就不能用了

用最新版 然后去直播间获取最新的 cookie

**Comment by xuzhihans** [comment]
> 用最新版 然后去直播间获取最新的 cookie

嗯 知道了 所以越来越难了 但是我们还是希望项目能够坚持住 : )

**Comment by Borber** [comment]
> > 用最新版 然后去直播间获取最新的 cookie
> 
> 嗯 知道了 所以越来越难了 但是我们还是希望项目能够坚持住 : )

嗯,没事, 总有解决办法
