### ISSUE TITLE
抖音又g了

### ISSUE THREAD

**Issue by unknownUser99999** [Borber/seam#237]
http://pull-l3.douyincdn.com/stage/stream-123338311118_or4.flv: Server returned 403 Forbidden (access denied)

**Comment by liuyongqing1** [comment]
是的 我也这样

**Comment by Borber** [comment]
请发送出现此情况的房间号在此 issue

**Comment by liuyongqing1** [comment]
573716250978

**Comment by liuyongqing1** [comment]
我这没问题了

**Comment by unknownUser99999** [comment]
> 请发送出现此情况的房间号在此 issue

这个不太方便吧，少儿不宜
