### ISSUE TITLE
能否增加arm的编译版本

### ISSUE THREAD

**Issue by zasl** [Borber/seam#25]
能否增加arm的编译版本

**Comment by Borber** [comment]
> 能否增加arm的编译版本

我尝试一下， 应该问题不大

**Comment by Borber** [comment]
![FireShot Capture 006 - Release v0 1 7 · Borber_test_ci - github com](https://user-images.githubusercontent.com/30563826/215389059-7e8d7f9d-0270-48aa-9351-2fc6faef520d.png)


即将支持 arm 编译版本， 近期发布 尽情期待

**Comment by Borber** [comment]
arm 已支持， 还请试用并反馈bug
