### ISSUE TITLE
Bili-弹幕支持-协作

### ISSUE THREAD

**Issue by Borber** [Borber/seam#29]
@eweca-d  晚上好, 我发现 https://github.com/Borber/seam/pull/28 合并之后无法直接编译运行, 应该有两个点卡住了, 一个是 ws 的地址可能不对, 我修改完ws地址 ( wss://dsa-cn-live-comet-01.chat.bilibili.com:2245/sub  **通过下方api可获取**) 之后开始不再卡住而是在下方位置报 `message: Err(Protocol(ResetWithoutClosingHandshake))`, 所以我认为应该是旧的地址没法返回有效数据所以卡住.

https://github.com/Borber/seam/blob/33e5444af34259ee58d6f1e3c439172dcaecaac4/src/live/bili.rs#L197-L199 

我找到了一个更好的 api `https://api.live.bilibili.com/xlive/web-room/v1/index/getDanmuInfo?id=<RID>` 可以获取 ws 地址, 

对于 `message: Err(Protocol(ResetWithoutClosingHandshake))` , 我目前不是很清楚, 稍微搜了一下可能与[这个](https://dev.binance.vision/t/rust-websocket-disconnects-ok-to-just-reconnect/5740), 即使用了sleep有关, 还麻烦大佬再抽时间看看,

**Comment by eweca-d** [comment]
对不起，忘了说我还没修完呢。只是先修改了conflict的部分，就被喊出去参加饭局，后续还有完成默认弹幕实现的部署。我今晚看看争取修完发一个pr。

**Comment by Borber** [comment]
哈哈哈 没事, 不急, 新年快乐啊.

**Comment by Borber** [comment]
我后续先支持其他平台和开始研究自动录制的方案, 弹幕这块就等大佬的第一版出来我们再陆续支持

**Comment by eweca-d** [comment]
新年快乐呀。我提交了一个新pr，我测试下来，弹幕功能是正常的了。然后新pr已经改成了你提议的那个cli命令格式啦。请查收。

**Comment by eweca-d** [comment]
测试和pr效率太高啦，点赞！这点倒是提醒了我，我发现未开播的直播间没有设置提示未开播后自动退出的功能....这个是反直觉的，下次提交pr的时候顺道修复下这个。

**Comment by eweca-d** [comment]
嗯的，我是用的vscode + rust analyzer，这一套基本提示是有的，就是说声明宏忘了写某些use之类的是可以有提示的，但宏编写的体验仍然是rust ide的一个痛点，只能说尽量不要写太复杂的宏了不然写的人和reviewer估计都头晕。

**Comment by Borber** [comment]
https://github.com/Borber/seam/commit/d247113b84a2975315ed90b46782ae4f8420a4da  大佬，你看一下这个分支我稍微修改了部分内容, 你看和你构思的有出入吗， 主要修改了 decode_and_record_danmu 的约定，不传入 recorder，

https://github.com/Borber/seam/blob/d247113b84a2975315ed90b46782ae4f8420a4da/src/danmu.rs#L99

 以及返回标准弹幕结构体， 还有就是把弹幕的处理迁移到了 danmu.rs 模块 

https://github.com/Borber/seam/blob/d247113b84a2975315ed90b46782ae4f8420a4da/src/danmu.rs#L45-L50

https://github.com/Borber/seam/blob/d247113b84a2975315ed90b46782ae4f8420a4da/src/danmu.rs#L148-L156

还有就是稍微修改了一下bili弹幕获取的方式

**Comment by eweca-d** [comment]
我最初的想法是，将对于格式化输出到终端，格式化保存至文件的“格式化标准”下放至各平台具体去实现可能会是一个比较好的想法，因为即使是保存弹幕文件，也是一份一份的，没有不同平台之间保持相同格式的需求。但我也不反对统一制定弹幕格式体，因为有助于不同平台之间弹幕保存标准化的推进。

具体到这次更改的话，我觉得：

1. 可以先把`DanmuBody`时间戳直接加上，这次分支可以先时间戳使用解码当时的时间戳，待我下次加上。
2. 219行那个最好别用`msg_type == "DANMU_MSG`，而是用`msg_type.starts_with("DANMU_MSG")`，貌似有些弹幕会有奇奇怪怪的后缀。
3. 那个别扭的type-mapping是我转写real-url的，确实意义不大。但是否可以为`DanmuBody`增加`type: String`属性，我只是目前只输出普通弹幕，但是可能会有保存礼物，SC等弹幕的需求咧。
4. 215行先new一个空白的结构体应该意义不大，可以直接等后面serde后直接new一个结构体。

**Comment by eweca-d** [comment]
哦哦，另外，我想说能不能考虑下将目前的 `-d`调整为`-D`，然后新增一个`-d`，内容是bool，作用是默认实现，即直接输出到终端 + 保存弹幕文件至`房间标题 + 弹幕截取命令开始的时间戳`。然后，弹幕文件选择通用的txt格式。

比如：

1. `seam bili 6 -d` => 直接输出到终端 + 保存至默认文件名的路径
2. `seam bili 6 -D abc.txt` => 保存至abc.txt文件中
3. `seam bili 6 -D abc` => 仅输出至终端（由于未以txt结尾）
4. `seam bili 6 -d -D abc.txt` => 返回错误，提示不支持同时使用-d和-D命令

也有考虑-D的参数复杂化，比如使用`命令%路径;`这种形式，将前面**包围的内容作为命令来解析，比如t代表终端，f代表文件，d代表数据库，那么`t;f%abc.txt;d%abc.sqlite`，就能代表同时输出到终端，写入文件，写入数据库。不知道你怎么看。

但总之我是会提议设置`-d`作为默认实现（输出到终端 + 写入默认文件名的文件）中，感觉这个会是最频繁被使用到的，因为自己决定并写入文件名实在太太太麻烦了。后者比较适合让GUI这种来调用。

**Comment by Borber** [comment]
我比较倾向于统一全平台的格式, 这样后期不管是适配保存文件还是其他持久化都会更方便, 其次是我们的结构体可以适当扩充必要字段以匹配所有的平台, 所有的弹幕无外乎是 人 时间 内容 这三个字段. 统一格式的好处会方便后续输出字幕文件, 或存数据库之类的功能

1. 好的 时间戳这取本地时间应该没问题, 后面解析的时候从第一个时间开始算时间差应该也没问题
2. `msg_type == "DANMU_MSG"` , 因为看bili很多资料上 `"DANMU_MSG"` 这个字段还是一直没变过的, 所以直接判等了,这块我其实之前的想法是只保存普通弹幕来着,  后期想法是通过弹幕信息生成可以被播放器直接播放的字幕文件, 这时候 礼物 sc 的处理就不太方便了. 
3. 结构体这块确实不太优雅, 哈哈哈, 之后学习一下大佬的写法

**Comment by Borber** [comment]
`-D` 没问题的, 这块我之前也有考虑过这块的内容. 默认文件名采取 rid_时间戳 ? 

> 3. `seam bili 6 -D abc` => 仅输出至终端（由于未以txt结尾）

这个我觉得没有必要进行判定, 因为可能有人选择输出其他后缀的文件, 或者有linux的用户想要无后缀的文件, 还有保存纯文本的弹幕这个需求和输出弹幕字幕文件的需求是否有重合区域还未知, 后面如果能输出字幕文件了也可以让用户选择保存字幕文件类型中添加一个纯文本选项

**Comment by eweca-d** [comment]
哈哈，我没注意看时间戳这方面的，假如websocket返回的消息里本来就有时间戳，那么可以用那个时间戳，否则的话可以用解析时候的时间戳。

start_with那个是real-url有个注释写道，可能会出现普通弹幕类型变成"DANMU_MSG:4:0:2:2:2:0"这种的，所以说real-url也是用start_with判断了下这种情况。至于弹幕类型，礼物和sc（特别是SC），放字幕里问题也是不大的啦，不然看的时候谢SC谢礼物却看不到谁送的，SC写了啥，也蛮奇怪的。

结构体写得很好拉，就是我看到代码里是先使用空白的“”new完之后，再改，感觉没必要，可能就是当时没注意到这个部分哈哈。

**Comment by eweca-d** [comment]
大部分直播间每次的标题略有不同吧，哔哩哔哩录播姬是默认存到rid-yyyymmdd-时间戳-本次直播标题，我觉得是一个挺不错的主意。

嗯，这倒是我疏忽了linux用户。但是如果不考虑非windows用户的需求的话，其实固定文件格式蛮重要的，因为咱们保存至文件的内容格式是固定的，而不同文件格式对于内容的格式是有不同需求的吧。

`-d`作为默认选项，保存文件和输出终端同时有，我是觉得这样可能有一种全家桶的感觉，蛮方便的。至于单独还是混合，可以做到`-D`里精细化控制，比如我那个以%分割的命令式风格的提案，可以是解决这些精细化选项的问题的一种办法。

**Comment by Borber** [comment]
1. 时间戳这块其实最后还是算相对时间的, 因为要和录制的视频对应上,所以本地直接生成应该没问题, 弹幕的时间戳有的平台可能有, 有的没有可能会不整齐, 
2. sc 和礼物这块, 因为不是所有平台都支持, 我们可否直接解析为另类弹幕如: `user: xxx, content: 【SC】大佬牛逼!` `user: xxx, content: 【礼物】 摩天大楼`， 类似这样的， 因为大多数平台还不支持这种类型， 或者在字母上的呈现我们可能大概率也会选择这种带符号的引起注意的方式， 而无法真的实现和官方类似的效果
3. 很多东西都是现学（可能带上了之前Java中的一些习惯），飞速成长ing， 多谢大佬

**Comment by Borber** [comment]
本次直播标题这块是我之前忽略了， 很久之前的 python版本其实有写入这个， 我会把这个字段加到 Node 里， 每个平台都适配上， GUI 应该也是需要这块信息的， 还有直播封面图， 但是封面图 cli 应该用不上， 考虑后面给 Node 的魔改一下

**Comment by eweca-d** [comment]
1. 时间戳这个倒无所谓，decode函数直接返回danmubody结构体里带时间戳的话，等同于每个平台可以按照自己的情况来独立实现时间戳。
2. 我一个想法是，type这一块，不使用enum而是string，这样不管平台支不支持，都无所谓啦。大不了有的平台只支持普通弹幕，type就全是“danmu”就好。支持的SC就写SC就好啦。直接解析到content的缺点是会有类型擦除，擦除后无法判断前面【】里的是被擦去的类型还是弹幕自带的内容。但是在转化成字幕文件的时候，可以解析成带前缀【SC】的形式。
3. 互相学习哈哈，rust我也是有好多要学。
4. 那可以考虑node各种信息后，再做默认文件名保存的实现。

**Comment by Borber** [comment]
对于 `-D` 这块我又想了一下, 如果直播间标题这块处理好了的话, 可以引入配置文件, 将其格式和命名方式 如 `rid-yyyymmdd-时间戳-本次直播标题` 固定到配置文件中, 这样的话 -D 就直接编程控制开关就好了

`-d` 默认还是不要直接写入文件, 仅输出到终端好了

![image](https://user-images.githubusercontent.com/30563826/213630547-37711e87-b45c-4960-9d85-eb772f699b97.png)

**Comment by eweca-d** [comment]
个人觉得使用配置文件是OK的，但会希望配置文件使用json。然后就是建议增加个config.rs专门处理配置的事情，再搞个struct Config啥的。然后程序一开始的时候，在fn main里使用oncecell库读到全局不可变变量里去。

**Comment by Borber** [comment]
> 个人觉得使用配置文件是OK的，但会希望配置文件使用json。然后就是建议增加个config.rs专门处理配置的事情，再搞个struct Config啥的。然后程序一开始的时候，在fn main里使用oncecell库读到全局不可变变量里去。

可以的, 这个也和我的想法一致, 我曾在别的项目中用过 

https://github.com/Borber/Whisperer/blob/bd21b12b271c65fe76525713d201390121dc67d2/whisperer/src/config.rs#L7-L39

但当时使用的时 toml, 配置文件为什么希望时json呢? 比较好奇

**Comment by eweca-d** [comment]
写那个comment的时候没想起toml。想的是已经用了serde_json，接着用json一致性比较好，而且json的可读性确实不赖，会的人也多。toml也不错。json的缺点是没法写注释，toml的缺点是如果有嵌套我觉得挺麻烦的。选哪个我觉得都挺OK的。

**Comment by Borber** [comment]
那就直接用json吧， 也比较方便后面server端 ，

直播间标题这块开始逐步支持了， 录制这块正在学习录播姬的方案 另找到一个项目似乎支持无缝拼接。 也正在学习中

祝除夕快乐

**Comment by eweca-d** [comment]
非常期待标题部分的完成和录制功能哈哈。

除夕快乐~
