### ISSUE TITLE
直播码率

### ISSUE THREAD

**Issue by YZHWOOD** [Borber/seam#3]
部分直播只能获取720P的直播源，而且码率也很低，不知道有没有什么办法可以实现获取不同码率的直播源

**Comment by Borber** [comment]
哪些直播呢?

**Comment by YZHWOOD** [comment]
例如B站的直播我在直播间看的直播的分辨率是1080P的，但是通过你的工具获取的直播源只有720P，还有比赛的直播都是可以选择蓝光，超清之类的可以选择

**Comment by Borber** [comment]
> 例如B站的直播我在直播间看的直播的分辨率是1080P的，但是通过你的工具获取的直播源只有720P，还有比赛的直播都是可以选择蓝光，超清之类的可以选择

我去看一下 我记得B站api 返回的 直播源 里面有几个可以选 不知道是不是 选错了

**Comment by Borber** [comment]
> 例如B站的直播我在直播间看的直播的分辨率是1080P的，但是通过你的工具获取的直播源只有720P，还有比赛的直播都是可以选择蓝光，超清之类的可以选择

你在B站直播 的播放界面 右键看一下统计信息 然后 再在本地对比一下 我这边 只要网页最高是 1080 本地就是1080  网页是720 本地也就是720
