### ISSUE TITLE
请问打开软件就闪退

### ISSUE THREAD

**Issue by Jalen-Wang** [Borber/seam#34]
小白请问，每次点开seam.exe闪出一个黑色dos视窗半秒后消失，然后什么事都没发生，软件也没启动，是不是我使用方式错误呢??

**Comment by Borber** [comment]
在命令行使用哈.

![image](https://user-images.githubusercontent.com/30563826/213667606-9b1f7fee-8ed6-4cb2-bb5b-905d2d1b61ec.png)

![image](https://user-images.githubusercontent.com/30563826/213667769-eaadb4b2-eb43-40af-9a7f-44b49a17ef0a.png)
