### ISSUE TITLE
修改main.exe名称后某些抖音直播出错。

### ISSUE THREAD

**Issue by 01bbbbb** [Borber/seam#35]
报错如下：
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\live\douyin.rs:40:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
搜索了下，$env:RUST_BACKTRACE=1 cargo run；RUST_BACKTRACE=full ./main。
但是不会用。
稍微理解下了错误信息，改回main.exe恢复正常。

另：抖音未获取到最高清晰度链接。
[
  {
    "format": "flv",
    "url": "http://pull-flv-l6.douyincdn.com/third/stream-xxxxxxxxxxxxxxxxxxxxx_uhd.flv"
  },
  {
    "format": "m3u",
    "url": "http://pull-hls-l6.douyincdn.com/third/stream-xxxxxxxxxxxxxxxxxxxxx_hd/index.m3u8"
  }
]
目前的是这两个，发现删除后缀_uhd、_hd后清晰度均有增加，因为没有抖音账号，无法分辨是否为最高清晰度。
另外，有些房间删除后变为纯音频流，不清楚是不是播放器解码的问题，也没有多次测试。

**Comment by Borber** [comment]
提供一下出错的房间号

理论上修改软件名是没有影响的, 清晰度这块我稍后修复一下

**Comment by Borber** [comment]
你看一下新版本的, 我修复了抖音的部分逻辑, 添加了直播间标题的获取

**Comment by 01bbbbb** [comment]
SEAM> ./test.exe douyin xxxxxxxxxxx
{
  "title": "xxxxxxxxxxxxxxxxxx",
  "nodes": [
    {
      "format": "flv",
      "url": "http://pull-flv-l26.douyincdn.com/third/stream-xxxxxxxxxx.flv"
    },
    {
      "format": "m3u",
      "url": "http://pull-hls-l26.douyincdn.com/third/stream-xxxxxxxxx.m3u8"
    }
  ]
}

随便找了个试了下，应该没问题了，辛苦了。
一个小问题，有没有必要文字标注其他清晰度链接修改的方式，也包括其他平台。
好像都是pc，很少存在码率带宽低的问题，但如果有通过这种方式集成移动端播放器做成app，可能会有需要（不懂技术，瞎猜的，只是看到just-live和iceliveviewer那种联想到的）。

另外，简化获取到的链接，像douyin，只是格式不同，douyu，只是cdn不同。其他的没有测试。


像斗鱼，real_url里有另外一种链接https://hw1a.douyucdn2.cn/live/#####r#########.flv?wsAuth=############&token=web-h5-0-#######-#########################&logo=0&expire=0&did=10000000000000000000000000001501&pt=2&st=0&origin=tct&mix=0&isp=&pushdouyu=1
我自己用这种会比短链接的延迟低一点。

哦，又发现斗鱼的标题获取好像有问题：
 ./test.exe douyu XXXXX
  "title": "douyu"
不过不太重要。

**Comment by Borber** [comment]
斗鱼的标题获取还没支持 目前只支持了 b站 cc 抖音 ， 所以默认返回 douyu 

目前只打算提供清晰度最高的链接， 后期如果很多人提出需求会考虑添加

**Comment by Borber** [comment]
是的 主要提供的就是最高清资源的 不同 格式和CDN 的链接，

**Comment by Borber** [comment]
如果使用过程中遇到其他问题也请积极提issue 我会及时处理的

**Comment by 01bbbbb** [comment]
> 如果使用过程中遇到其他问题也请积极提issue 我会及时处理的

好的。
请看新的issue。
