### ISSUE TITLE
虎牙 未开播录像轮播显示错误？

### ISSUE THREAD

**Issue by 01bbbbb** [Borber/seam#36]
SEAM> .\test.exe huya 123888
{"count":0,"data":[{"gameLiveInfo":{"activityCount":0,"activityId":0,"attendeeCount":1562203,"avatar180":"https://huyaimg.msstatic.com/avatar/1089/7c/1bad570ccab5732e7962853248aa59_180_135.jpg?1594724739","bitRate":0,"bussType":1,"cameraOpen":0,"channel":909992191,"codecType":0,"contentIntro":"","gameFullName":"DOTA2","gameHostName":"dota2","gameType":0,"gid":7,"introduction":"开始发病","isSecret":0,"level":0,"liveChannel":909992191,"liveCompatibleFlag":0,"liveId":"7189581514854134275","liveSourceType":0,"multiStreamFlag":0,"nick":"Sccc丶","privateHost":"873956860","profileHomeHost":"873956860","profileRoom":123888,"recommendStatus":0,"recommendTagName":"","roomName":"","screenType":0,"screenshot":"http://img.live.yy.com/cdnimage/video/default_live.jpg?1674273","sex":2,"shortChannel":0,"startTime":1673954899,"totalCount":1562203,"uid":909992191,"yyid":873956860},"gameStreamInfoList":[]}],"iFrameRate":0,"iWebDefaultBitRate":0,"vMultiStreamInfo":[]}
未开播
使用的real_url虎牙python显示如下：
输入虎牙直播房间号：
123888
该直播间源地址为：
直播录像：//hw-vod.cdn.huya.com/record/huyalive/909992191-909992191-3908386699960385536-1820107838-10057-A-0-1-imgplus_500/2023-01-17-19:28:47_2023-01-18-01:28:47.m3u8?hyvid=823418433&hyauid=909992191&hyroomid=909992191&hyratio=350&hyscence=livereplay&appid=66&domainid=17&srckey=NjZfMTdfODIzNDE4NDMz&bitrate=500&client=81&definition=350&pid=909992191&scene=livereplay&vid=823418433
请按任意键继续. . .

但实际上也不能播放。
不清楚有没有修复的必要。

**Comment by 01bbbbb** [comment]
real_url的链接加上http：前缀就可以播放了。
所以应该有修复的必要性了。

**Comment by Borber** [comment]
下午修复这块 因为我之前一直没找到轮播的直播间所以没有适配这块

**Comment by Borber** [comment]
v0.1.15 已修复多余信息输出, 但轮播这块毕竟不是直播, 所以还是不作为开播处理

**Comment by 01bbbbb** [comment]
v0.1.15windows defender 报毒。

Trojan:Script/Wacatac.H!ml
严重
特洛伊木马

另：本issue已完成，作关闭处理。
