### ISSUE TITLE
Bilibili获取直播间信息出错

### ISSUE THREAD

**Issue by eweca-d** [Borber/seam#38]
请尝试长期直播的直播间id:

- "6" LOL
- "13" DOTA2

使用这两个RID会错误的提示直播间不存在，经过检查，这是由于`get_real_room_info`返回了`None`。此函数中`resp`确实返回了数据，但是在紧接着的一步正则提取时，发生了问题。

此外，`real-url`是可以正确的获取直播流的url的。

**Comment by Borber** [comment]
稍等， 我去查看一下

**Comment by Borber** [comment]
已找到问题所在， 半小时之后修复

**Comment by Borber** [comment]
已修复, 更换了获取方式

**Comment by Borber** [comment]
![image](https://user-images.githubusercontent.com/30563826/213914342-26f76faa-c095-4a6e-99c5-e4868f08a9c0.png)

**Comment by eweca-d** [comment]
OK了，尝试了几个其他rid也OK了，6啊，效率！
