### ISSUE TITLE
【建议】能直接粘贴链接，然后自动识别房间号返回视频流地址吗

### ISSUE THREAD

**Issue by liyoushow** [Borber/seam#39]
感觉每次用都得手动输入对应平台+房间号有点繁琐，我代码水平不是很高，只知道大概能用正则解决这个问题，希望作者能考虑下这个功能，万分感激

**Comment by Borber** [comment]
cli 端目前的设计是这样的， 仅作为工具或者说是接口来使用， 用户可以使用脚本来实现批量/自动获取，GUI 将实现订阅及界面选择，敬请期待
