### ISSUE TITLE
未完成列表中的爬取主播名称建议取消

### ISSUE THREAD

**Issue by icimence** [Borber/seam#4]
因为有一些官方的直播间的标题会撞，然后有一些主播的ID反而比较复杂，更适合自定义，可以作为保留选项，但是希望还是能够使用自定义命名，另外图形界面我可以试试，看看能不能做出来，目前倾向于electron-vue或者qt到时候看看。

**Comment by icimence** [comment]
打包为可执行文件已经尝试，但是发现有一个无法避免的障碍就是需要一个设置项的文件夹和一个输出文件夹，没事实现完全打包为一个可执行文件

**Comment by Borber** [comment]
> 因为有一些官方的直播间的标题会撞，然后有一些主播的ID反而比较复杂，更适合自定义，可以作为保留选项，但是希望还是能够使用自定义命名，另外图形界面我可以试试，看看能不能做出来，目前倾向于electron-vue或者qt到时候看看。

收到 这次重构我会重视这个问题的

**Comment by Borber** [comment]
rust 重构第一版 已取消主播名称， 后续将以更好地结构组织数据， 图形界面后续应该会采用 tauri
