### ISSUE TITLE
探讨一下douyin获取直链的方案。

### ISSUE THREAD

**Issue by youshandefeiyang** [Borber/seam#40]
douyin现阶段找到两个接口，其中一个就是本项目用的，请求需要携带cookie，[这一行](https://github.com/Borber/seam/blob/5119eb9a98924414995667a0cd04c74fa313d0f7/src/live/douyin.rs#L23) ，我也是用自己抓的固定的cookie做请求，现阶段是公共API每天很多人用，还是想改为随机获取cookie，就是先请求一次，从服务端获取cookie然后保存，第二次请求时候携带上一次获取的cookie，这样就能避免每次都是相同的cookie，不过我现阶段获取到的值还是有些问题

现在一直用以下的接口，不需要携带cookie，不过需要获取room_id
`https://live.douyin.com/webcast/room/info_by_scene/?aid=6383&live_id=1&device_platform=web&language=zh-CN&enter_from=web_search&cookie_enabled=true&screen_width=1920&screen_height=1080&browser_language=zh-CN&browser_name=Chrome&room_id=xxxxxxxxxxxxxxxxx&scene=pc_stream_4k`

**Comment by Borber** [comment]
没事， 后续cli将提供本地化设置以及server端提供缓存来解决这个问题

**Comment by youshandefeiyang** [comment]
![58B69BBE-7AEA-45B0-84AE-CA2EA5013E7A](https://user-images.githubusercontent.com/63959400/214622138-dfd30ef0-34da-4ccf-867e-fb581e71a387.png)
我和一位大师详细交流记录，分析抖音通过检测浏览器BOM环境，随机分配cookie，然后携带cookie就可以从接口获取内容

**Comment by Borber** [comment]
这个有一个不太方便的就是 roomid 这块用户手动获取的话不是很方便，（PC端）而通过 web 链接获取roomid又需要用到cookie， 以及不是很了解是否 roomid是固定不变的

**Comment by Borber** [comment]
经过测试， cookie 的检测并不严格， 修改数个字符后仍然通过请求， 所以后面将使用随机 cookie

**Comment by youshandefeiyang** [comment]
还是想研究一下，究竟是缺失了什么东西，为何浏览器一请求就携带cookie，考虑是浏览器BOM环境，我也是最近才开始准备做一个all in one整合一下这些平台，直播平台抖快需要携带cookie，其他大部分平台不携带，总之这玩意就是个不稳定因素，想着解决一下，之前用PHP写的性能和稳定性都不大行，准备用Golang重写一下

**Comment by youshandefeiyang** [comment]
先就这样吧，我从RealTools这个项目找到这里的，他也是用的固定cookie，没有人逆向一下看看这块究竟是缺啥，头疼

**Comment by Borber** [comment]
这块我感觉没啥可逆向的， cookie 也不是对应账号的， 没有登陆的时候就有了。 然后验证也不严格，所以直接随机cookie也没有什么问题， 目前也没发现cookie时效情况。 

其他平台其实也有携带 cookie的情况。

现在大家都喜欢用 rust或者golang重写小工具 哈哈哈

**Comment by Borber** [comment]
为什么不选择我大rust呢？

**Comment by eweca-d** [comment]
@youshandefeiyang 既然有这个想法，其实可以尝试下rust。这个项目不是很多生命周期，其实难度和java和golang没啥区别的。

**Comment by youshandefeiyang** [comment]
确实没有必要逆向，刚才有了新发现，我将cookie清除后，访问`live.douyin.com`，发现响应头已经返回了Set-Cookie，那么就容易多了，在请求接口前首先请求一次`live.douyin.com`，然后保存cookie，第二次直接请求接口并且携带上一次的cookie，就解决了这类问题，我试着看了下快手，响应头也会返回Set-Cookie

**Comment by Borber** [comment]
赞, 很久以前写python爬虫的时候好像也遇到过这种情况.

**Comment by youshandefeiyang** [comment]
是的，我刚才简单用php写了一下，后期准备都用golang重写了 @Borber 
https://github.com/youshandefeiyang/IPTV/blob/main/PHP/douyin.php

**Comment by Borber** [comment]
呜呜呜, 不要投奔 golang嘛, rust 多可爱

**Comment by youshandefeiyang** [comment]
对rust不熟悉，这语法还是太麻烦，想多长点头发。。。。。。

**Comment by eweca-d** [comment]
@youshandefeiyang ，单纯就这个项目来说，如果会其他任意一种语言，真的一小时可以做到可以写rust提交pr的程度，作为一种现代语言，rust真的难度很低的（不写生命周期的话）。很容易的，不试试么。

**Comment by Borber** [comment]
> @eweca-d 你说得对，作为科班出身，不掌握四五门编程语言谈什么码农，不过我这人还是喜欢从简，你要说写这种，如果个人用，我更加推荐PHP或者Python，写起来十分钟都用不了，再看看静态语言，要不是为了性能和稳定性，公共API多人请求，我连Golang都懒得考虑，Rust和C++这种，我能不碰肯定不会碰的

确实是考虑到公共api这块如果用rust成本会低很多, 而且性能好一些. 不过我也是本身就很喜欢 rust
