### ISSUE TITLE
【协作】压缩弹幕的解压是否会导致弹幕顺序错位

### ISSUE THREAD

**Issue by Borber** [Borber/seam#44]
https://github.com/Borber/seam/blob/a0f5d639a7835d13753c2ed29b0e517884926740/src/live/bili.rs#L192-L206

这块是翻译 real-url 而来的， 我在考虑是否会出现压缩弹幕后面再重新插入会否导致顺序错位的问题， 我上周曾尝试解决，但在解压后数据的生命周期这块栽了跟头 😭

**Comment by Borber** [comment]
@eweca-d  大佬你的想法呢?

**Comment by eweca-d** [comment]
我在想，b站的弹幕一次性给的message的数量应当是以时间为切片的，所以差那么一两秒应该区别不大。如果有这方面的强迫症的话，或许我们可以写一个带生命周期的struct，里面包含compressed_flag，然后一次性serde再提取信息并string化到return vector里面？

如果有需要的话，我这两天pr一个试试？

**Comment by Borber** [comment]
这块如果大佬有兴趣做的话就再好不过了, 我也正好学习一下这块的知识. 但不着急, 我们慢慢来.

**Comment by eweca-d** [comment]
看来没问题，我close issue啦。
