### ISSUE TITLE
请问大佬是怎么在抖音直播链接规则变了之后分析到新的获取规则？谢谢。

### ISSUE THREAD

**Issue by yinjiaoyuan** [Borber/seam#47]
我看了https://github.com/Borber/seam/issues/11 很快就修复，请问大佬是如何分析抖音直播链接规则变了之后很快就分析到新规则的？是抓包分析吗？用了什么工具？谢谢。

**Comment by Borber** [comment]
简单的js逆向， 其实一般播放源都不会保护的太过严密。 以下是我的所有直播平台的分析步骤

1. 浏览器先进一个直播间， 打开开发者工具， 刷新， 查看网络
2. 看到直播流的请求后注意其特征id部分， 大多都是一串uuid或者其他组合名称
3. 在开发者工具>网络搜索uuid或直播流的其他特征字符串, 找到restful风格的api接口或者如果直接在直播间的页面请求中发现了数据的结构体

    - 如果找到了api 试着减少传参, 找到必要参数, 最后模拟请求
    - 如果在直播间页面发现了大量数据就直接使用正则匹配出数据部分然后解析它, 一般都是在 script 部分的 json 串

4. 完善成rust代码

可以看看 real-url 项目, python 代码可读性强, 当作教程看也无不可

**Comment by yinjiaoyuan** [comment]
谢谢大佬。
