### ISSUE TITLE
好像抖音的又不行了

### ISSUE THREAD

**Issue by yinjiaoyuan** [Borber/seam#48]
代码加了log看的话是抖音返回结果没有live-room-name这个字段。

**Comment by Borber** [comment]
稍等哈

**Comment by Borber** [comment]
提供一下房间号

我这边测试没问题

![image](https://user-images.githubusercontent.com/30563826/215732218-2357dcec-f8f4-4086-b7f5-c84f8bab8a11.png)

**Comment by yinjiaoyuan** [comment]
房间号是7194753884236040975
./seam douyin 7194753884236040975

**Comment by Borber** [comment]
![image](https://user-images.githubusercontent.com/30563826/215735803-e74278b0-987e-407d-96b6-43b174317d50.png)
 
房间号没这么长， 你是不是选错了？ 我这边用链接后面紧接的rid就好了， 不用想 real-url 那样去找 room_id

**Comment by yinjiaoyuan** [comment]
你测试的这个“祝哥哥姐姐发发发”的房间号是591902670010，我测试也是可以的。

**Comment by yinjiaoyuan** [comment]
我是从网页链接里面拿的房间号，链接是：

**Comment by yinjiaoyuan** [comment]
https://live.douyin.com/97456265029?cover_type=0&enter_from_merge=web_live&enter_method=web_card&game_name=&is_recommend=1&live_type=game&more_detail=&request_id=202301311815257C31E7F630080A0C179C&room_id=7194753884236040975&stream_type=vertical&title_type=1&web_live_page=hot_live&web_live_tab=all

**Comment by yinjiaoyuan** [comment]
我是从上面的网页链接里面拿的房间号，拿的是room_id那个值，应该是拿错了，97456265029才是。

**Comment by Borber** [comment]
![image](https://user-images.githubusercontent.com/30563826/215736583-2787dc4f-7712-4884-ad20-1de871d1179e.png)

是的, 我这边优化过, 不用去找那个了

**Comment by yinjiaoyuan** [comment]
好的，谢谢大佬！

**Comment by yinjiaoyuan** [comment]
我是看了https://github.com/Borber/seam/issues/40这个提到的room_id而用了这个参数，不过我今天用https://github.com/Borber/seam/issues/40提到的这个方法上午一直不行，到下午又可以了，好奇怪。

**Comment by Borber** [comment]
可能 api 不太稳定? 我没有详细测试那个, 因为参数不够方便

**Comment by Borber** [comment]
可以 但还是测试功能, seam douyin xxxx -R 会监听 自动开始录制

**Comment by pockyL991014** [comment]
现在实现的功能就是能当主播开播后 手动输入rid就可以开始录制了是嘛？

**Comment by Borber** [comment]
不是 现在就支持了 可以监听 rid 不过还在测试

**Comment by youshandefeiyang** [comment]
最近准备用Golang重写了，你可以参考一下
https://github.com/youshandefeiyang/IPTV/tree/main/Golang

**Comment by Borber** [comment]
> 最近开始用Golang重写了，你可以参考一下，后续增加其它平台 https://github.com/youshandefeiyang/IPTV/tree/main/Golang

好的好的， 对了， record 你打算怎么实现呀？

**Comment by Borber** [comment]
以及这个免责声明真的有用吗？ 我想这要不也搞一个

**Comment by youshandefeiyang** [comment]
要吧，加了当个心理安慰，录屏的话看看有没有ffmpeg库调用的，嫌麻烦直接shell调用ffmpeg算了，库还是python现成的多

**Comment by Borber** [comment]
> 要吧，加了当个心理安慰，录屏的话看看有没有ffmpeg库调用的，嫌麻烦直接shell调用ffmpeg算了，库还是python现成的多

我目前也在和 @eweca-d  讨论这块的问题，ffmpeg 直接打包进来太大了， 调库的话 eweca-d 也尝试过 还是要引入动态链接库，也不小， 不会精简就很麻烦。。。

**Comment by youshandefeiyang** [comment]
我就不弄录屏了，你可以写个教程，ffmpeg录屏的教程，让他们自己安装ffmpeg录制
