### ISSUE TITLE
是否可以尝试用 Boa 作为内嵌的 JS 执行引擎？

### ISSUE THREAD

**Issue by mzji** [Borber/seam#49]
[boa](https://github.com/boa-dev/boa) 是一个纯 Rust 实现的 JS 引擎，虽然目前尚不完善，但有测试一下的价值；如果可用，那么所有现在或未来存在的需要执行 js 才能获取直播流地址的场合都可以降低服务器开销和地址获取延迟。

**Comment by Borber** [comment]
> [boa](https://github.com/boa-dev/boa) 是一个纯 Rust 实现的 JS 引擎，虽然目前尚不完善，但有测试一下的价值；如果可用，那么所有现在或未来存在的需要执行 js 才能获取直播流地址的场合都可以降低服务器开销和地址获取延迟。

收到， 我会进行调研的， 感谢你的建议 😊

**Comment by Borber** [comment]
已经测试完了， 额可以运行， 近期更新

**Comment by Borber** [comment]
代码已更新， 下次发版即可使用
