### ISSUE TITLE
关于更详细的启动步骤

### ISSUE THREAD

**Issue by Harley-ZP** [Borber/seam#59]
感谢作者的分享，
但我可能因为没有rust经历，
我读完readMe也没看明白我应该按哪几步走，seam.exe又是哪来的😭
可以有更详细的说明嘛，我觉得会有利于广泛使用和反馈

**Comment by Borber** [comment]
从项目左边 release 下载最新版本压缩包， https://github.com/Borber/seam/releases/tag/v0.1.18  如果你是 windows 就选择 文件名包含 windows的， 

之后 解压到你的电脑， 使用 cmd 或者其他终端打开到他的目录 最后使用 readme 里的命令就好了

**Comment by Borber** [comment]
如果你愿意帮我宣传一下这个项目，我可以另写一个图文并茂的教程 🤣

**Comment by Harley-ZP** [comment]
> 从项目左边 release 下载最新版本压缩包， https://github.com/Borber/seam/releases/tag/v0.1.18 如果你是 windows 就选择 文件名包含 windows的，
> 
> 之后 解压到你的电脑， 使用 cmd 或者其他终端打开到他的目录 最后使用 readme 里的命令就好了

非常感谢，我刚才尝试了下斗鱼Ok，抖音好像会报错，你之前有这个情况嘛？不知道我是不是缺啥依赖
![image](https://user-images.githubusercontent.com/49360021/219300202-e8bff04e-5b1f-47dc-a80e-9cdec11e282c.png)

**Comment by Borber** [comment]
稍等一下， 抖音改了东西， 我修复之后还没发版

**Comment by Borber** [comment]
稍后下载 v0.1.19 版本即可

**Comment by Harley-ZP** [comment]
> 稍后下载 v0.1.19 版本即可

强，这效率也太高了🆒

**Comment by Borber** [comment]
![image](https://user-images.githubusercontent.com/30563826/219302628-e30cade5-67fe-4d8f-8603-73984864160f.png)
