### ISSUE TITLE
关于播放和录制

### ISSUE THREAD

**Issue by Harley-ZP** [Borber/seam#61]
昨天链接没问题了，今天我这边用了potpalyer没能播放成功哎，也在开播，直播号也没问题，作者用的啥试播放呀？
房间 \seam.exe douyin 80017709309
URL： http://pull-f3.douyincdn.com/third/stream-112514363894530731.flv

**Comment by Borber** [comment]
抱歉哈，检测了一下画蛇添足去除了的参数导致的无法正常播放， 稍后我修复一下

**Comment by Borber** [comment]
稍后下载 v0.1.20 即可 我是使用的 mpv 播放，目前测试没有问题

**Comment by Borber** [comment]
![Snipaste_2023-02-17_13-25-04](https://user-images.githubusercontent.com/30563826/219556759-560ee702-f1fe-420c-9d8d-63086b03eb6d.png)

**Comment by mzji** [comment]
项目首页那两个说明（一个斗鱼的一个抖音的）最好也改一下

**Comment by Borber** [comment]
> 项目首页那两个说明（一个斗鱼的一个抖音的）最好也改一下

好哒
