### ISSUE TITLE
抖音直播源的清晰度

### ISSUE THREAD

**Issue by latv666** [Borber/seam#62]
直播地址
https://live.douyin.com/732385677810

如果没开播的话从主机游戏区找个画质好的就行
https://live.douyin.com/category/1_4609

目前只能获取到一个 720P 的清晰度,而且只有 30 帧,有没有办法获取到所有清晰度,或者用参数获取不同的清晰度?

这条直播源是网页源码里找到的,1080P 60FPS
`http://pull-l3.douyincdn.com/third/stream-112528671176917471.m3u8?auth_key=1677416524-0-0-d413c445f15c28acb23adab388ec7a2b`

这条直播源是用 seam 获取到的,720P 30FPS
`http://pull-l3.douyincdn.com/third/stream-112528671176917471_hd.m3u8?auth_key=1677417994-0-0-e249d4460ee6c4ef12dc1af039f700e5`

另外输出打印的时候可以优化一下排版吗? 让直播源独占一行,这样可以用 ctrl+shift+→快速选取
"title":"xxxxx"
"format":"flv"
"url":
http://xxxxxxxxxxxxx

**Comment by Borber** [comment]
收到， 我去查看一下

**Comment by Borber** [comment]
已修复 稍后到 release 下载 v0.1.21， 后续有bug 还请继续积极反馈 ， 输出格式的话展示先将就一下， 后续再优化

**Comment by latv666** [comment]
收到,谢谢

**Comment by zg2345688** [comment]
大佬我遇到一个情况，有一个抖音直播间我抓取的地址只有720P，然后我去浏览器用开发者模式抓取的源地址，我直播间画质设置为原画的时候他的源地址还是720p，我换成其他清晰度就可以抓取到，这种情况咋解决啊，他原画的清晰度比肯定不是720P，而且我试了其他直播间是正常的，就这个直播间最高只能抓取到720p的清晰度这是为啥啊
