### ISSUE TITLE
linux如何使用

### ISSUE THREAD

**Issue by Eggsmemory** [Borber/seam#94]
之前使用的是streamlink
偶然发现大佬的项目
使用release:seam-v0.1.23.aarch64-unknown-linux-musl.tar.xz
系统:ubuntu 22.04
测试直播平台:pandalive
下载后解压两次，得到seam和config.json
安装ffmpeg
之后用./seam panda  giyoming
输出结果:-bash: ./seam: cannot execute binary file: Exec format error
再请作者帮忙解说一下linux用法
谢谢
另外请问19禁直播间是否需要登入才能录制呢？
如果可以录制会协助增强这个repo的

**Comment by Eggsmemory** [comment]
另外希望增加19禁的录制
尝试过windows可以录制韩国平台没有年龄限制的
但19禁的不知道是没有登入还是本来就没有写这个功能
都是显示未开播

**Comment by hellofuc1** [comment]
楼上此人，做色情的，大家不要理会这个人，

**Comment by Eggsmemory** [comment]
> 楼上此人，做色情的，大家不要理会这个人，

看看你的活动记录再来说别人吧
